trigger: none

pool:
  vmImage: windows-latest

jobs:
- job: TestARMTTK
  steps:
  - task: RunARMTTKTests@1
    inputs:
      templatelocation: '$(System.DefaultWorkingDirectory)'
      resultLocation: '$(System.DefaultWorkingDirectory)\ARM-TTK.XML'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)\*-armttk.xml'
    condition: always()
